myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("user/", include("user.urls")),
    path("", views.IndexMain.as_view()),
]

myapp/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

# from blog.views import Index # (클래스)

urlpatterns = [
    # path(패턴, 매핑) /blog/
    # path("", views.index), # FBV
    # 글 목록 조회
    path("", views.Index.as_view(), name="list"),
    # 글 상세 조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name="detail"),
    # 글 작성
    path("write/", views.Write.as_view(), name="write"),
    # 글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name="edit"),
    # 글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name="delete"),
    # 코멘트 작성
    path(
        "detail/<int:pk>/comment/write/", views.CommentWrite.as_view(), name="cm-write"
    ),
    # 코멘트 삭제
    path(
        "detail/comment/<int:pk>/delete/",
        views.CommentDelete.as_view(),
        name="cm-delete",
    ),
    # 태그 작성
    path(
        "detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name="tag-write"
    ),
    # 태그 삭제
    path(
        "detail/hashtag/<int:pk>/delete/",
        views.HashTagDelete.as_view(),
        name="tag-delete",
    ),
]

myapp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    # 외래키 설정, Post의 pk없어지면 같이 없어지도록 cascade
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    writer = models.CharField(max_length=10)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment on {self.post.title}"


class HashTag(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

myapp/blog/forms.py
# blog/forms.py

from django import forms
from .models import Post, Comment, HashTag


# Form 일반
# Model Form
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {"content": forms.Textarea(attrs={"rows": "3", "cols": "35"})}


class HashTagForm(forms.ModelForm):
    class Meta:
        model = HashTag
        fields = ["name"]

myapp/blog/views.py
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm
from django.urls import reverse_lazy, reverse

### Post
# def index(request):
#     if request.method == "GET":
#         return HttpResponse("Index page GET")
#     # 나머지 요청
#     # 에러, 예외처리
#     return HttpResponse("No!")


class Index(View):
    # method-get일때
    def get(self, request):
        # return HttpResponse("Index page GET class")

        # DB 접근해서 값을 가져옴
        # 게시판에 글 보여줘야하기 때문에 데이터베이스에서 값 조회
        post_objs = Post.objects.all()
        # context = DB에서 가져온 값
        context = {"posts": post_objs}
        # print(post_objs)
        return render(request, "blog/post_list.html", context)


# write
# post-form
# 글 작성 화면
def write(request):
    if request.method == "POST":
        # form 확인
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save()
            return redirect("blog:list")

    # get인 경우
    form = PostForm()
    return render(request, "blog/post_form.html", {"form": form})


# class (genericView 사용)
# django 자체의 클래스 뷰 기능 강력, 편리
#class List(ListView):
#    model = Post  # 모델
#    template_name = "blog/post_list.html"  # 템플릿
#    context_object_name = "posts"  # 변수 값의 이름


#class Write(CreateView):
#    model = Post  # 모델
#    form_class = PostForm  # 폼
#    success_url = reverse_lazy("blog:list")  # 성공시 보내줄 url

class Write(LoginRequiredMixin ,View):
    # Mixin: LoginRequiredMixin
    # 이 클래스를 상속받게 되면 로그인 된 사람만 접근가능
    def get(self, request): # 글 작성 화면
        form = PostForm()
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html', context)
    
    def post(self, request): # submit시 동작
        form = PostForm(request. POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer=request.user
            post.save()
            return redirect('blog:list')
        form.add_error(None, '폼이 유효하지 않습니다.')
        context = {
            'form': form
        }
        return render(request, 'blog/post_form.html')


class Detail(DetailView):
    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = "post"


class Update(UpdateView):
    model = Post
    template_name = "blog/post_edit.html"
    fields = ["title", "content"]
    # success_url = reverse_lazy("blog:list") 아래 함수로 작성해서 지움

    # initial 기능
    # form에 값을 미리 넣어주기 위해서서
    def get_initial(self):
        # UpdateView(부모)의 것을 갖고옴
        # 딕셔너리 형태
        initial = super().get_initial()
        # 이 Update 클래스 자체의 것
        # pk 기반으로 객체를 가져옴
        post = self.get_object()

        initial["title"] = post.title
        initial["content"] = post.content
        return initial

    # get_absolute_url
    def get_success_url(self):
        # pk 기반으로 현제 객체 가져오기
        post = self.get_object()
        return reverse("blog:detail", kwargs={"pk": post.pk})


class Delete(DeleteView):
    model = Post
    success_url = reverse_lazy("blog:list")


class DetailView(View):
    def get(self, request, pk):
        # 해당 글
        post = Post.objects.get(pk=pk)

        # 댓글
        comments = Comment.objects.filter(post=post)

        # 해시태그
        hashtags = HashTag.objects.filter(post=post)

        # 댓글 Form
        comment_form = CommentForm()

        # 해시태그 Form
        hashtag_form = HashTagForm()

        context = {
            "post": post,
            "comments": comments,
            "hashtags": hashtags,
            "comment_form": comment_form,
            "hashtag_form": hashtag_form,
        }

        # 넣어준 값이 있을 때 사용
        # 값들이 들어간 채로 페이지에 출력이 되도록 (템플릿 안에 값 넣어서 출력)
        return render(request, "blog/post_detail.html", context)


### Comment
class CommentWrite(View):
    # def get(self, request):
    #     pass
    def post(self, request, pk):
        form = CommentForm(request.POST)
        if form.is_valid():
            # 사용자에게 댓글 내용 받아옴
            content = form.cleaned_data["content"]
            # 해당 아이디에 해당하는 글 불러옴(댓글은 어떤 한 글의 댓글이므로)
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성
            comment = Comment.objects.create(post=post, content=content)
            return redirect("blog:detail", pk=pk)


class CommentDelete(View):
    def post(self, request, pk):
        # 지울 객체를 찾음 (댓글 객체)
        comment = Comment.objects.get(pk=pk)
        # 상세페이지로 돌아감
        post_id = comment.post.id
        # 삭제
        comment.delete()

        return redirect("blog:detail", pk=post_id)


### Hashtag
class HashTagWrite(View):
    def post(self, request, pk):
        form = HashTagForm(request.POST)
        if form.is_valid():
            # 사용자에게 태그 내용 받아옴
            name = form.cleaned_data["name"]
            # 해당 아이디에 해당하는 글 불러옴(댓글은 어떤 한 글의 댓글이므로)
            post = Post.objects.get(pk=pk)
            # 댓글 객체 생성
            hashtag = HashTag.objects.create(post=post, name=name)
            return redirect("blog:detail", pk=pk)


class HashTagDelete(View):
    def post(self, request, pk):
        # 해시태그의 pk(id)
        # 해시태그 불러오기
        hashtag = HashTag.objects.get(pk=pk)
        # 포스트의 pk(id)값 가져오기
        post_id = hashtag.post.id
        # 해시태그 삭제
        hashtag.delete()
        # 응답
        return redirect('blog:detail', pk=post_id)

myapp/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <title>블로그</title>
  </head>
  <body>
    <div class="container">
      <h1>Blog</h1>
      {% block content %} {% endblock %}
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
      integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
      integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

myapp/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
  <hr>
  <h2>제목:
    {{ post.title }}</h2>

  <a href="{% url 'blog:edit' pk=post.pk %}" class="btn">수정</a>
  <form action="{% url 'blog:delete' pk=post.pk %}" method="post">
    {% csrf_token %}
    <input type="submit" value="삭제" class="btn">
  </form>

  <p>내용:
    {{ post.content }}</p>
  <p>작성자:
    {{ post.writer }}</p>
  <p>작성일:
    {{ post.created_at }}</p>

  <hr>

  <!-- 댓글 작성 화면 -->
  <h3>댓글</h3>
  <form action="{% url 'blog:cm-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form.content }}
    <input type="submit" value="댓글 작성">
  </form>
  <br>
  <!-- comments -->
  {% if comments %}
    <ul>
      {% for comment in comments %}
        <!-- 내용, 작성시간, 삭제 버튼 -->
        <li>{{ comment.content }}
          /
          {{ comment.created_at }}
          <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="X" class="btn">
          </form>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>댓글이 없습니다.</p>
  {% endif %}
  <hr>

  <!-- 태그 작성 화면 -->
  <h3>해시태그</h3>
  <form action="{% url 'blog:tag-write' pk=post.pk %}" method="post">
    {% csrf_token %}
    {{ hashtag_form.name }}
    <input type="submit" value="태그 작성">
  </form>

  <br>

  {% if hashtags %}
    <ul>
      {% for hashtag in hashtags %}
        <li>{{ hashtag }}</li>
        <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
          {% csrf_token %}
          <input type="submit" value="X">
        </form>
      {% endfor %}
    </ul>
  {% endif %}

  <hr>
  {% comment %} <a href="{% url 'blog:list' %}">목록</a> {% endcomment %}
  <form method="get" action="{% url 'blog:list' %}">
    {% csrf_token %}
    <input type="submit" value="목록">
  </form>
{% endblock %}

myapp/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.title.label_tag }}
    <input type="text" name="{{ form.title.name }}" value="{{ form.initial.title }}">
    <br>
    {{ form.content.label_tag }}
    <textarea type="text" name="{{ form.content.name }}">{{ form.initial.content }}</textarea>
    <br>
    <input type="submit">
  </form>

{% endblock %}

myapp/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %} {% block content %}
<p>블로그 글 작성 화면</p>
<form action="{% url 'blog:write' %}" method="post">
  {% csrf_token %}
{% comment %} <label for="title">제목</label>
  <input type="text" id="title" placeholder="제목을 입력해주세요." />

  <br />
  <label for="content">내용</label>
  <input type="text" id="content" placeholder="내용을 입력해주세요." />
  <br /> {% endcomment %}
  {{ form.as_p }}

  <input type="submit" class="btn btn-primary" />
</form>
{% endblock %}

myapp/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %} {% block content %}
<h2>블로그 게시판 화면</h2>
<p>블로그 게시판 첫 화면입니다.</p>
<a href="{% url 'blog:write' %}" class="btn btn-outline-success">글작성</a>

<!-- context -->
{# {{ posts }} #}

<!-- 글이 있을 때 -->
<!-- 테이블 -->

<!-- 조건문/순회문 -->
<!-- 글이 없을 때 -->
<!-- 글이 없습니다. -->

<!-- 글이 있을 때: 테이블 출력 -->

{% if posts %}
<table class="table table-bordered">
  <thead class="table-light">
    <tr>
      <td>title</td>
      <td>content</td>
      <td>writer</td>
    </tr>
  </thead>
  <tbody>
    {% for post in posts %}
    <tr>
      <td>
        <a href="{% url 'blog:detail' pk=post.pk %}" class="btn"
          >{{ post.title }}</a
        >
      </td>
      <td>{{ post.content }}</td>

      <td>{{ post.writer }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<!-- 글이 없을 때 :문구 출력 -->
{% else %}
<p>작성된 게시물이 없습니다.</p>
{% endif %} {% endblock %}